"""C6 Guardrails client SDK."""

from ._version import __version__
from .client import GatewayClient, GatewayClientOptions
from .errors import (
    AuthenticationError,
    FirewallBlockError,
    GatewayError,
    GatewayUnavailableError,
    RateLimitError,
)
from .sync_client import SyncGatewayClient
from .transport import Transport, from_dict
from .types import (
    ChatCompletionChoice,
    ChatCompletionChunk,
    ChatCompletionChunkChoice,
    ChatCompletionRequest,
    ChatCompletionResponse,
    ChatCompletionUsage,
    ChatMessage,
    CqScanRequest,
    CqScanResult,
    EmbeddingData,
    EmbeddingRequest,
    EmbeddingResult,
    EmbeddingUsage,
    GatewayHealth,
    ModerationCategories,
    ModerationCategoryScores,
    ModerationRequest,
    ModerationResult,
    ModerationResultItem,
    PipelineTrace,
    PipelineTraceStage,
    ScanRequest,
    ScanResult,
    SemanticMatch,
)

__all__ = [
    "__version__",
    "from_dict",
    "Transport",
    "GatewayClient",
    "GatewayClientOptions",
    "SyncGatewayClient",
    "GatewayError",
    "FirewallBlockError",
    "RateLimitError",
    "AuthenticationError",
    "GatewayUnavailableError",
    "GatewayHealth",
    "ScanRequest",
    "ScanResult",
    "SemanticMatch",
    "PipelineTrace",
    "PipelineTraceStage",
    "CqScanRequest",
    "CqScanResult",
    "ChatMessage",
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "ChatCompletionChoice",
    "ChatCompletionUsage",
    "ChatCompletionChunk",
    "ChatCompletionChunkChoice",
    "EmbeddingRequest",
    "EmbeddingResult",
    "EmbeddingData",
    "EmbeddingUsage",
    "ModerationRequest",
    "ModerationResult",
    "ModerationResultItem",
    "ModerationCategories",
    "ModerationCategoryScores",
]
