FROM node:24-alpine AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY . .
ARG VITE_BUILD_TYPE
ENV VITE_BUILD_TYPE=$VITE_BUILD_TYPE
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx-demo.conf /etc/nginx/nginx.conf
EXPOSE 80 443
